### ISSUE TITLE
Is there a sample Go app which uses this library?

### ISSUE THREAD

**Issue by SubOptimal** [warpfork/go-testmark#9]
After watching the GPN20 recording [Testmark: a Markdown Convention for Test Fixtures and Data](https://media.ccc.de/v/gpn20-70-testmark-a-markdown-convention-for-test-fixtures-and-data)
I wanted to try out go-testmark.

After having a closer look, I realized that `go-testmark` is a golang library and not a "ready to run app". So I would need to write a tool myself to use it. Do you know if there is an app which uses this library?

**Comment by warpfork** [comment]
The examples from the slides deck are actually links :grin: -- you can follow them from https://slides.com/warpfork/testmark#/9/1 , and the couple of pages below that (hit spacebar to progress to next-slide).

Here are some of those links extracted:

- In [IPLD](https://ipld.io/) specs:
  - Source, raw: https://raw.githubusercontent.com/ipld/ipld/756520d4744b8c4b90097d99ab8b93ac87983327/specs/selectors/fixtures/selector-fixtures-1.md
  - As rendered on Github: https://github.com/ipld/ipld/blob/756520d4744b8c4b90097d99ab8b93ac87983327/specs/selectors/fixtures/selector-fixtures-1.md
  - As rendered in a website: https://ipld.io/specs/selectors/fixtures/selector-fixtures-1/
  - Code executing those: https://github.com/ipld/go-ipld-prime/blob/37f875b8e4c89ef768a0e0f952d2af0644f91b3a/traversal/selector/spec_test.go
- In [Warpforge](http://warpforge.io/) documentation:
  - Source, raw: https://raw.githubusercontent.com/warpfork/warpforge/5be2023bdb45c0aa0db599b10c7c17b8bd0d168a/examples/100-formula-parse/example-formulas.md
  - As rendered on Github: https://github.com/warpfork/warpforge/blob/5be2023bdb45c0aa0db599b10c7c17b8bd0d168a/examples/100-formula-parse/example-formulas.md
  - (no website for this one, this project hasn't bothered yet -- github rendering is good enough!)
  - Code executing those: https://github.com/warpfork/warpforge/blob/5be2023bdb45c0aa0db599b10c7c17b8bd0d168a/wfapi/formula_spec_test.go#L19-L32

**Comment by warpfork** [comment]
I also recently saw someone start using line numbers from testmark hunks as part of their test failure messages, which seems neat: https://github.com/ipld/go-datalark/commit/82b8d0f90d118ea8cfc28c857400100bc39532ad

... there's a lot of other testmark example setup in there, too, which might be another fun source to look at.  Some of it is very cool, because that project involves an interpreted language, so it's actually got "executable" script hunks and their outputs paired together as tests!

**Comment by warpfork** [comment]
Come to think of it, you could actually use the [testexec](https://github.com/warpfork/go-testmark/tree/master/testexec) extension package in this same repo as a good example -- if I had to highlight some lines to focus on, probably these in particular show the heart of it: https://github.com/warpfork/go-testmark/blob/61f37951573f092ebea37c8e38f2202cb5352800/testexec/testexec.go#L222-L300

**Comment by warpfork** [comment]
Hope these examples help!

If you end up producing more, please comment with them!  It would be a joy to see :)
